apiVersion: v1
kind: Service
metadata:
  name: wisecow
spec:
  type: LoadBalancer  # Use NodePort if running locally
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: wisecow
